2019-11-02 16:34:09,057 ERROR: Exception on /admin_show_posts [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 204, in admin_show_posts
    Post.query.remove(name=name)
AttributeError: 'BaseQuery' object has no attribute 'remove'
2019-11-02 16:35:25,857 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:36:25,650 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:38:09,322 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:38:13,862 ERROR: Exception on /admin_show_posts [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 206, in admin_show_posts
    db.session.remove(post)
TypeError: remove() takes 1 positional argument but 2 were given
2019-11-02 16:39:20,735 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:39:22,016 ERROR: Exception on /admin_show_posts [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 206, in admin_show_posts
    db.session.delete(post)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1994, in delete
    self._delete_impl(state, instance, head=True)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in _delete_impl
    "Instance '%s' is not persisted" % state_str(state)
sqlalchemy.exc.InvalidRequestError: Instance '<Post at 0x416e770>' is not persisted
2019-11-02 16:39:23,775 ERROR: Exception on /admin_show_posts [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 206, in admin_show_posts
    db.session.delete(post)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1994, in delete
    self._delete_impl(state, instance, head=True)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in _delete_impl
    "Instance '%s' is not persisted" % state_str(state)
sqlalchemy.exc.InvalidRequestError: Instance '<Post at 0x42459d0>' is not persisted
2019-11-02 16:39:28,298 ERROR: Exception on /admin_show_posts [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 206, in admin_show_posts
    db.session.delete(post)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1994, in delete
    self._delete_impl(state, instance, head=True)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in _delete_impl
    "Instance '%s' is not persisted" % state_str(state)
sqlalchemy.exc.InvalidRequestError: Instance '<Post at 0x439a5d0>' is not persisted
2019-11-02 16:40:04,940 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
