2019-11-02 16:28:23,009 ERROR: Exception on /admin_show_posts [GET] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2019-11-02 16:30:16,935 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:30:18,734 ERROR: Exception on /admin_show_posts [GET] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 207, in admin_show_posts
    return render_template('admin_show_posts.html', user=user, posts=posts,lenght=len(Post.query.all()))
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\new_microblog\microblog\app\templates\admin_show_posts.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "G:\new_microblog\microblog\app\templates\admin_show_posts.html", line 14, in root
    <p>
  File "G:\new_microblog\microblog\app\templates\base.html", line 55, in root
    <h2>Магазин видеоигр</h2>
  File "G:\new_microblog\microblog\app\templates\admin_show_posts.html", line 26, in block_content
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-11-02 16:31:44,758 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:31:53,336 ERROR: Exception on /admin_show_posts [GET] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 207, in admin_show_posts
    return render_template('admin_show_posts.html', user=user, posts=posts,lenght=len(Post.query.all()))
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\new_microblog\microblog\app\templates\admin_show_posts.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "G:\new_microblog\microblog\app\templates\admin_show_posts.html", line 14, in root
    {{ form.name.label }}<br>
  File "G:\new_microblog\microblog\app\templates\base.html", line 55, in root
    <h2>Магазин видеоигр</h2>
  File "G:\new_microblog\microblog\app\templates\admin_show_posts.html", line 26, in block_content
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-11-02 16:32:22,254 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 16:32:43,463 ERROR: Exception on /admin_show_posts [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 204, in admin_show_posts
    Post.query.delete(name=name)
TypeError: delete() got an unexpected keyword argument 'name'
2019-11-02 16:33:57,523 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
