2019-11-01 23:32:09,856 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-01 23:32:20,637 ERROR: Exception on /edit_profile [POST] [in c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\new_microblog\microblog\app\routes.py", line 147, in edit_profile
    db.session.commit()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1027, in commit
    self.transaction.commit()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 494, in commit
    self._prepare_impl()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
    self.session.flush()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2470, in flush
    self._flush(objects)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2568, in _flush
    flush_context.execute()
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\gembelton\pycharmprojects\untitled6\venv\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('Fill', '', 4)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-11-01 23:41:30,927 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 14:03:59,639 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 14:35:47,423 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 15:11:41,103 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 15:14:13,120 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 15:29:56,245 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 15:55:00,009 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
2019-11-02 15:56:23,179 INFO: Microblog startup [in G:\new_microblog\microblog\app\__init__.py:36]
